### PR TITLE
1.0.8

### PR DESCRIPTION
**Pull request by agolyud**
Add app Services

### CODE REVIEW

**Comment by agolyud** [comment]
@khoben Hi, any ideas on how to improve the code? Maybe allow adding other apps from the list of installed ones?

**Comment by agolyud** [comment]
@khoben Hi, any ideas on how to improve the code? Maybe allow adding other apps from the list of installed ones?

**Comment by khoben** [comment]
> Maybe allow adding other apps from the list of installed ones?

Hi,

Yes, fetching applications from [context.packageManager.getInstalledApplications()](https://developer.android.com/reference/android/content/pm/PackageManager#getInstalledApplications(int)) - is a good idea. 

For example, in byeDpi it is implemented like this: https://github.com/romanvht/ByeDPIAndroid/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fio%2Fgithub%2Fdovecoteescapee%2Fbyedpi%2Ffragments%2FAppSelectionFragment.kt

**Comment by agolyud** [comment]
> > Maybe allow adding other apps from the list of installed ones?
> 
> Hi,
> 
> Yes, fetching applications from [context.packageManager.getInstalledApplications()](https://developer.android.com/reference/android/content/pm/PackageManager#getInstalledApplications(int)) - is a good idea.
> 
> For example, in byeDpi it is implemented like this: https://github.com/romanvht/ByeDPIAndroid/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fio%2Fgithub%2Fdovecoteescapee%2Fbyedpi%2Ffragments%2FAppSelectionFragment.kt

Let me try to implement it tomorrow. Will you see how I do it?

**Comment by khoben** [comment]
> Let me try to implement it tomorrow. Will you see how I do it?

Sure, let me know when it's ready.

**Comment by agolyud** [comment]
@khoben Hello. I can't solve the problem with displaying all applications on Android 12 and above. I threw it together quickly for now on the main screen. Any ideas?

**Comment by khoben** [comment]
> @khoben Hello. I can't solve the problem with displaying all applications on Android 12 and above. I threw it together quickly for now on the main screen. Any ideas?

Have you tried declaring `QUERY_ALL_PACKAGES` permission?

```xml
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" tools:ignore="QueryAllPackagesPermission" />
```

**Comment by agolyud** [comment]
No, I didn't use it, now everything works

**Comment by agolyud** [comment]
@khoben It seems I've finished the list of applications (let's see when you have time, maybe you'll make some changes)

**Pull request merged**
