### PR TITLE
Fixes & Improvements

### PR DESCRIPTION
**Pull request by khoben**
- Add Outline `prefix` support
- Add reading connection string from filesystem
- And other ui & logic fixes

Tested on Android TV: Xiaomi Mi Stick 4K (Android 11), Xiaomi Mi TV (Android 11)

<details>
  <summary>Changes list</summary>
  
- Add `prefix` support
- Pass connection URL via parameters instead of static vars
- Handle VPN Service state with BroadcastReceiver
- Fix: notifications wont show without `setSmallIcon`
- Add stop button to foreground service
- Make `ShadowSocksInfo` parcelable
- Add connection string validation
- Try to extract server name from connection string after # symbol
- Add `isConnectionLoadingState` while VPN service preparing connection
- `ServerIconProvider`, `ParseUrlOutline` classes instead of similar functions
- `AndroidViewModel` replaced with `ViewModel`
- `ViewModel` constructor dependency injection with `ViewModel.Factory`
- Fix layout bound with ripple animation
- Disallow opening `ServerDialog` while VPN is active
- Add reading connection url from file
- Fix `coil` disk caching with `respectCacheHeaders(false)`
- Add missing `ic_github` icon
- Disable `forceDarkAllowed`

</details>

Sample apk: https://github.com/khoben/VPN_Outline_TV/releases/download/1.0.5-mod/OutlineVPNTv-1.0.5-mod.apk

### CODE REVIEW

**Comment by agolyud** [comment]
@khoben Thank you for the work done. I fixed the time display. And also added you to the development.

**Comment by agolyud** [comment]
@khoben If you have no objections to my comment, then I'll join the Merge PR

**Comment by khoben** [comment]
> @khoben If you have no objections to my comment, then I'll join the Merge PR

Great.
Also fixed Compose Preview and added a border for buttons when they are in focus (so you can see them better on TV).
I think that's it, we can merge the changes.

**Comment by agolyud** [comment]
@khoben Added app updates. See the commit

**Comment by khoben** [comment]
> @khoben Added app updates. See the commit

Moved the application update logic to the UpdateManager interface.  Checked, the application is updated. But I think it's worth making the apk downloading from the background service and then show install button.

**Comment by khoben** [comment]
This is fine for now. Then it can be done better in other PRs.

**Pull request merged**
